### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by berserk82** [greggman/webgl2-fundamentals#12]
Hello everyone.
I found your website while searching for learning material for WebGL (it was linked in Quora)
I would like to know if there is a good printed book about WebGL (I know there are many, but I'm asking for advice).
I have a decent programming background and I don't mind using "standard" OpenGL or GLES API for compilers, I just want to dig in WebGL, and in this field I'm really a beginner.
Overall, the suggested book should use a minimum math because it's one of my main weakness.

Thanks in advance for any help.

Bye, Ivano.

**Comment by greggman** [comment]
I don't personally know any books to recommend.

As for OpenGL, vs OpenGL ES or WebGL they are similar but not the same. WebGL pretty much requires JavaScript and uses JavaScript. OpenGL and OpenGL ES both require C/C++. At basic level they are the same API but things are different because the languages are diferent. Also their environments make them different. For example to load a image in OpenGL you generally read a file, call some library like libpng or libjpeg (or write your own) and then upload it to the GPU all in sequence. In WebGL though images are usually downloaded which means they happen asynchronously which means the code that uses them is different. Similarly in C/C++ many apps have a main loop that just runs forever. in WebGL though you're not allowed to do that. The browser just executes events and it requires that all events exit relatively quickly. That means the structure of your code is usually different in WebGL vs OpenGL/OpenGL ES. Not that different but different.

As for math this site covers a bunch of the basic math. If there are questions you have feel free to ask here on in the comments on the specific pages.

**Comment by berserk82** [comment]
Ok, let's assume I pick a good book about WebGL by reading reviews and tables of contents.
Now, I would like to know if math in WebGL features some kind of library or if I'll have to code my own.
In the latter case, I'm afraid WebGL is not my thing yet.
Please, give me advice on this.

Bye, Ivano.

**Comment by greggman** [comment]
Neither WebGL nor OpenGL provide math library. You pick one and use that or write your own. Any book on OpenGL or WebGL will include or recommend a math library. This site creates one during the articles.

**Comment by berserk82** [comment]
Thanks a lot.
I guess WebGL is not for me, then. I have serious problems with math in general, guess with 3D math like vectors and matrices.

Thanks anyhow for your help.

Bye, Ivano.
