### ISSUE TITLE
trying to get your color demo to work from webgl2

### ISSUE THREAD

**Issue by jacobbogers** [greggman/webgl2-fundamentals#48]
I was trying to do the color demo (from the fundamentalswebgl2 using glFragcoord)

But cant get it to work, could you please take a look

https://github.com/jacobbogers/testings   branch `removeVSLogic`

in `master` it works with the vectorshader in your example of `gl_FragCoord` it doesnt seem to work (readpixel returns all zeros)

the source is in /src/ex3/

to build 
`git checkout removeVSLogic`
`npm i`
`npm run build` (webpack build in directory /dist)
`http-server dist/`   (go browser and look at console output  you will see a typedarray with only zeros)

my first webgl program from scratch)

What am I doing wrong?

thanks very much in advance

**Comment by stefnotch** [comment]
So, [one of those changes broke it](https://github.com/jacobbogers/testings/compare/master...removeVSLogic)

If I had to guess why it happens, I'd guess that it's because
```glsl
gl_Position = vec4(0, 0, 0, 1);
```
in the vertex shader causes all the points to be drawn at `(0,0,0)` which causes them to get clipped (near plane) and thus not get drawn at all.

**Comment by jacobbogers** [comment]
True, that, I will ask in stack overflow, excuse the inconvenience
