### ISSUE TITLE
why is the gl_pointSize so large

### ISSUE THREAD

**Issue by jacobbogers** [greggman/webgl2-fundamentals#49]
in your prev example you set gl_PointSize to 100.0, when i change the value to 1.0 the sample produces mostly zeros (less for the 3rd average) 
why is that?

### fragment shader
```glsl
void main() {
  gl_Position = vec4(0, 0, 0, 1);
  gl_PointSize = 100.0;
}
```

### vertext shader
```glsl
const fs = `#version 300 es
precision highp float;
uniform sampler2D tex;
uniform int numArrays;
out vec4 outColor;
void main() {
  int level = 0;
  int start = int(gl_FragCoord.x);
  ivec2 size = textureSize(tex, level);
  vec4 color = vec4(0);
  for (int y = 0; y < size.y; ++y) {
    for (int x = start; x < size.x; x += numArrays) {
      color += texelFetch(tex, ivec2(x, y), level);
    }
  }
  outColor = color / float(size.x / numArrays * size.y);
}
```

## JS snippet
````javascript

  const prg = twgl.createProgramFromSources(gl, [vs, fs]);

  const numArraysLoc = gl.getUniformLocation(prg, "numArrays");

  const tex = gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D, tex);
  // so we don't need mips
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
  // so we can pass a non multiple of 4 bytes
  gl.pixelStorei(gl.UNPACK_ALIGNMENT, 1);

  const numArrays = 5;
  const values = new Uint8Array([
     1, 1, 1, 1, 1,
     2, 150, 231, 9, 71,
     3, 129, 290, 3, 90,
     4, 141, 300, 2, 80,
     5, 123, 212, 4, 75,
  ]);
  const width = values.length;
  const height = 1;
  gl.texImage2D(gl.TEXTURE_2D, 0, gl.R8, width, height, 0, gl.RED, gl.UNSIGNED_BYTE, values);
  
  gl.canvas.width = numArrays;
  gl.canvas.height = 1;
  gl.viewport(0, 0, numArrays, 1);

  gl.useProgram(prg);
  gl.uniform1i(numArraysLoc, numArrays);
  gl.drawArrays(gl.POINTS, 0, 1);
```

**Comment by greggman** [comment]
gl_PointSize is in pixels. If you set it to 1 only 1 pixel is going to be draw for the 1 point we're drawing. 

I use `gl_PointSize` and draw with `gl.POINTS` because it's absolute simplest shader to show off some feature unrelated to buffers and attributes. In the case above things will work as long as `gl_PointSize` is larger than or equal to the size of the area you're trying to draw to (except for the fact that there is a maximum point size)

https://webglstats.com/webgl2/parameter/ALIASED_POINT_SIZE_RANGE

In your previous question https://github.com/greggman/webgl2-fundamentals/issues/47 you asked about `gl_FragCoord`. I didn't need to setup buffers, attributes, and vertex arrays to answer that question and putting all that code in would have just cluttered the example.
